<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-26T21:09:22 IST" name="Default Suite" finished-at="2022-12-26T21:11:52 IST" duration-ms="149408">
    <groups>
    </groups>
    <test started-at="2022-12-26T21:09:22 IST" name="Test.TestUserDelete_Chrome" finished-at="2022-12-26T21:09:53 IST" duration-ms="30305">
      <class name="Test.TestUserDelete">
        <test-method is-config="true" signature="before_Class(org.testng.ITestContext)[pri:0, instance:Test.TestUserDelete@46cc127b]" started-at="2022-12-26T21:09:22 IST" name="before_Class" finished-at="2022-12-26T21:09:36 IST" duration-ms="13921" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@305e95a4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="deleteUserfromList()[pri:0, instance:Test.TestUserDelete@46cc127b]" started-at="2022-12-26T21:09:36 IST" name="deleteUserfromList" finished-at="2022-12-26T21:09:49 IST" duration-ms="13162" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to locate the element]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to locate the element
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.element(webAction.java:332)
at Pages.UserCreationandUserDelete.searchforUser(UserCreationandUserDelete.java:85)
at Pages.UserCreationandUserDelete.validateUserCreation(UserCreationandUserDelete.java:95)
at Test.TestUserDelete.deleteUserfromList(TestUserDelete.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:116)
at Test.TestNGXML.main(TestNGXML.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUserfromList -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult,org.testng.ITestContext)[pri:0, instance:Test.TestUserDelete@46cc127b]" started-at="2022-12-26T21:09:49 IST" name="getResult" finished-at="2022-12-26T21:09:50 IST" duration-ms="939" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deleteUserfromList status=FAILURE method=TestUserDelete.deleteUserfromList()[pri:0, instance:Test.TestUserDelete@46cc127b] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@305e95a4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.TestUserDelete@46cc127b]" started-at="2022-12-26T21:09:50 IST" name="logoutFromApplication" finished-at="2022-12-26T21:09:53 IST" duration-ms="2082" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:116)
at Test.TestNGXML.main(TestNGXML.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.TestUserDelete -->
    </test> <!-- Test.TestUserDelete_Chrome -->
    <test started-at="2022-12-26T21:09:53 IST" name="Test.LoginTest_Chrome" finished-at="2022-12-26T21:10:24 IST" duration-ms="30994">
      <class name="Test.LoginTest">
        <test-method is-config="true" signature="before_Class(org.testng.ITestContext)[pri:0, instance:Test.LoginTest@1b58ff9e]" started-at="2022-12-26T21:09:53 IST" name="before_Class" finished-at="2022-12-26T21:10:04 IST" duration-ms="10994" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@55e42684]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="loginTest()[pri:0, instance:Test.LoginTest@1b58ff9e]" started-at="2022-12-26T21:10:04 IST" name="loginTest" finished-at="2022-12-26T21:10:21 IST" duration-ms="17831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult,org.testng.ITestContext)[pri:0, instance:Test.LoginTest@1b58ff9e]" started-at="2022-12-26T21:10:21 IST" name="getResult" finished-at="2022-12-26T21:10:22 IST" duration-ms="104" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=SUCCESS method=LoginTest.loginTest()[pri:0, instance:Test.LoginTest@1b58ff9e] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@55e42684]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.LoginTest@1b58ff9e]" started-at="2022-12-26T21:10:22 IST" name="logoutFromApplication" finished-at="2022-12-26T21:10:24 IST" duration-ms="2046" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:116)
at Test.TestNGXML.main(TestNGXML.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.LoginTest -->
    </test> <!-- Test.LoginTest_Chrome -->
    <test started-at="2022-12-26T21:10:24 IST" name="Test.TestUserCreation_Chrome" finished-at="2022-12-26T21:11:00 IST" duration-ms="36628">
      <class name="Test.TestUserCreation">
        <test-method is-config="true" signature="before_Class(org.testng.ITestContext)[pri:0, instance:Test.TestUserCreation@585811a4]" started-at="2022-12-26T21:10:24 IST" name="before_Class" finished-at="2022-12-26T21:10:31 IST" duration-ms="7540" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@18d610e1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="userCreation()[pri:0, instance:Test.TestUserCreation@585811a4]" started-at="2022-12-26T21:10:31 IST" name="userCreation" finished-at="2022-12-26T21:10:58 IST" duration-ms="26704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult,org.testng.ITestContext)[pri:0, instance:Test.TestUserCreation@585811a4]" started-at="2022-12-26T21:10:58 IST" name="getResult" finished-at="2022-12-26T21:10:58 IST" duration-ms="290" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=userCreation status=SUCCESS method=TestUserCreation.userCreation()[pri:0, instance:Test.TestUserCreation@585811a4] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@18d610e1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.TestUserCreation@585811a4]" started-at="2022-12-26T21:10:58 IST" name="logoutFromApplication" finished-at="2022-12-26T21:11:00 IST" duration-ms="2076" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:116)
at Test.TestNGXML.main(TestNGXML.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.TestUserCreation -->
    </test> <!-- Test.TestUserCreation_Chrome -->
    <test started-at="2022-12-26T21:11:00 IST" name="Test.leaveTest_Chrome" finished-at="2022-12-26T21:11:36 IST" duration-ms="35986">
      <class name="Test.leaveTest">
        <test-method is-config="true" signature="before_Class(org.testng.ITestContext)[pri:0, instance:Test.leaveTest@16afbd92]" started-at="2022-12-26T21:11:00 IST" name="before_Class" finished-at="2022-12-26T21:11:09 IST" duration-ms="8404" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@528e5e38]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="applyleave()[pri:0, instance:Test.leaveTest@16afbd92]" started-at="2022-12-26T21:11:09 IST" name="applyleave" finished-at="2022-12-26T21:11:34 IST" duration-ms="25036" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to locate the element]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to locate the element
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.element(webAction.java:332)
at Pages.leavepagee.applyLeave(leavepagee.java:62)
at Test.leaveTest.applyleave(leaveTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:116)
at Test.TestNGXML.main(TestNGXML.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applyleave -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult,org.testng.ITestContext)[pri:0, instance:Test.leaveTest@16afbd92]" started-at="2022-12-26T21:11:34 IST" name="getResult" finished-at="2022-12-26T21:11:34 IST" duration-ms="503" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=applyleave status=FAILURE method=leaveTest.applyleave()[pri:0, instance:Test.leaveTest@16afbd92] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@528e5e38]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.leaveTest@16afbd92]" started-at="2022-12-26T21:11:34 IST" name="logoutFromApplication" finished-at="2022-12-26T21:11:36 IST" duration-ms="2027" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:116)
at Test.TestNGXML.main(TestNGXML.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.leaveTest -->
    </test> <!-- Test.leaveTest_Chrome -->
    <test started-at="2022-12-26T21:11:36 IST" name="Test.EmployeeDownloadTest_Chrome" finished-at="2022-12-26T21:11:52 IST" duration-ms="15405">
      <class name="Test.EmployeeDownloadTest$TestUserCreation">
        <test-method is-config="true" signature="before_suite()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5ca17ab0]" started-at="2022-12-26T21:09:22 IST" name="before_suite" finished-at="2022-12-26T21:09:22 IST" duration-ms="159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_suite -->
        <test-method is-config="true" signature="before_Class(org.testng.ITestContext)[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5ca17ab0]" started-at="2022-12-26T21:11:36 IST" name="before_Class" finished-at="2022-12-26T21:11:43 IST" duration-ms="7112" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@16391278]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="userCreation()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5ca17ab0]" started-at="2022-12-26T21:11:43 IST" name="userCreation" finished-at="2022-12-26T21:11:49 IST" duration-ms="5935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult,org.testng.ITestContext)[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5ca17ab0]" started-at="2022-12-26T21:11:49 IST" name="getResult" finished-at="2022-12-26T21:11:50 IST" duration-ms="296" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=userCreation status=SUCCESS method=EmployeeDownloadTest$TestUserCreation.userCreation()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5ca17ab0] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@16391278]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5ca17ab0]" started-at="2022-12-26T21:11:50 IST" name="logoutFromApplication" finished-at="2022-12-26T21:11:52 IST" duration-ms="2046" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:116)
at Test.TestNGXML.main(TestNGXML.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5ca17ab0]" started-at="2022-12-26T21:11:52 IST" name="closeDriver" finished-at="2022-12-26T21:11:52 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- Test.EmployeeDownloadTest$TestUserCreation -->
    </test> <!-- Test.EmployeeDownloadTest_Chrome -->
  </suite> <!-- Default Suite -->
</testng-results>
